version: '3'
services:
    web:
        image: m8377/plc_app_ufv
        ports:
            - 5000:5000
            - 80:5000
        depends_on:
            - rq-server
            - rq-dashboard
            - rq-worker-orders
        restart: always
    rq-server:
        image: redis:alpine
        ports:
          - 6379:6379
        restart: always
    rq-dashboard:
      image: jaredv/rq-docker:0.0.2
      command: rq-dashboard -H rq-server
      ports:
        - 9181:9181
    rq-worker-orders:
      image: m8377/plc_app_ufv
      command: rq worker -u redis://rq-server:6379 orders
      depends_on:
        - rq-server
      restart: always
    ouroboros:
      container_name: ouroboros
      hostname: ouroboros
      image: pyouroboros/ouroboros
      environment:
        - CLEANUP=true
        - INTERVAL=60
        - LOG_LEVEL=info
        - SELF_UPDATE=true
        - TZ=America/Vancouver
        - LATEST=true
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock