version: '2'
services:
    web:
        image: m8377/plc_app_ufv
        ports:
            - 5000:5000
        volumes:
            - .:/code
        depends_on:
            - rq-server
            - rq-dashboard
            - rq-worker
            - rq-worker-orders
        restart: always
    rq-server:
        image: redis:alpine
        ports:
          - 6379:6379
        restart: always
    rq-dashboard:
      image: jaredv/rq-docker:0.0.2
      command: rq-dashboard -H rq-server
      ports:
        - 9181:9181
    rq-worker:
      image: jaredv/rq-docker:0.0.2
      command: rq worker -u redis://rq-server:6379 high normal low
      volumes:
        - .:/usr/src/app
      depends_on:
        - rq-server
    shepherd:
      image: mazzolino/shepherd
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - SLEEP_TIME="30s"